piwheels/db.py
piwheels/piwheels.sql

Make sure transactions are kept short, cursors are closed as soon as
possible, and added a couple of indexes that ought to help with the big
join and a few other queries.

Tidy up the DB code a bit

---

.gitignore
piwheels/db.py
piwheels/web_index.py

As du -sh is now taking nearly 4 minutes to run!

Use a database query instead of du -sh

---

deploy_slave.sh
docs/slave_protocol.dot
piwheels/__init__.py
piwheels/master/__init__.py
piwheels/master/db.py
piwheels/master/states.py
piwheels/monitor/__init__.py
piwheels/slave/__init__.py
piwheels/slave/builder.py
sql/create_piwheels.sql
sql/update_piwheels_04_to_05.sql

This branch expands the file handling of the database and the master to "generate" (actually just symlink) ARMv6 wheels from ARMv7 wheels. It also simplifies some of the database interaction, adds a load of doc-strings, and splits all the state classes into their own module (the master's main module was getting a tad crowded).

ARMv6 Wheels

---

Makefile
docs/sense.rst
piwheels/importer/__init__.py
piwheels/initdb/__init__.py
piwheels/master/__init__.py
piwheels/remove/__init__.py
piwheels/slave/__init__.py
piwheels/slave/builder.py
piwheels/terminal.py
tests/conftest.py
tests/importer/test_importer.py
tests/initdb/test_initdb.py
tests/master/test_big_brother.py
tests/master/test_db.py
tests/master/test_lumberjack.py
tests/master/test_master.py
tests/master/test_pypi.py
tests/master/test_seraph.py
tests/master/test_slave_driver.py
tests/master/test_states.py
tests/remove/test_remove.py
tests/slave/test_builder.py
tests/slave/test_slave.py
tests/test_systemd.py

Finish off the test suite so it covers everything except the monitors (that is, everything we actually use to manipulate the system, and the system itself). A few bugs fixed along the way, nonetheless it's a stupidly huge PR...

Test suite

---

piwheels/__init__.py
piwheels/initdb/sql/create_piwheels.sql
piwheels/initdb/sql/update_piwheels_0.12_to_0.13.sql
piwheels/master/cloud_gazer.py
piwheels/master/db.py
piwheels/master/mr_chase.py
piwheels/master/pypi.py
piwheels/master/the_oracle.py
piwheels/remove/__init__.py
piwheels/terminal.py
tests/initdb/test_initdb.py
tests/master/test_cloud_gazer.py
tests/master/test_db.py
tests/master/test_mr_chase.py
tests/master/test_pypi.py
tests/master/test_the_oracle.py
tests/remove/test_remove.py
tests/test_terminal.py

Fixes #103 and #108, and the total build time statistic.

Upgraded cloud gazer, PyPI scraper, etc.

---

piwheels-master.service
piwheels/__init__.py
piwheels/sense/__init__.py
piwheels/sense/renderers.py

Bring the SenseHAT monitor up to date since the move to CBOR and protocol-checked messages.

Fix Sense HAT monitor

---

piwheels/initdb/sql/create_piwheels.sql
piwheels/initdb/sql/update_piwheels_0.14_to_0.15.sql

Use UTC timezone with all timestamp comparisons (because all timestamps
in the db are in the UTC timezone). And always use column names in
INSERTs; doesn't matter to new installations but the crusty old master
has one table with a different column order.

Fix a couple of db issues

---

piwheels/master/big_brother.py
piwheels/master/slave_driver.py
tests/master/test_big_brother.py

Reduce duplicates

---

piwheels/slave/__init__.py
tests/slave/test_slave.py

Even when terminated by systemd, QUIT message, etc.

Ensure slave always sends BYE on shutdown

---

deploy_slave.sh

Re: https://github.com/piwheels/packages/issues/23

Add libadios-dev packages to build clients for package 'openPMD-api'

---

README.rst

Not worth merging until we have released on PyPI

Add status badges to readme

---

docs/conf.py
piwheels/__init__.py
piwheels/initdb/sql/create_piwheels.sql
piwheels/initdb/sql/update_piwheels_0.16_to_0.17.sql
piwheels/logger/__init__.py
piwheels/master/cloud_gazer.py
piwheels/master/db.py
piwheels/master/pypi.py
piwheels/master/templates/project.pt
piwheels/master/the_oracle.py
piwheels/master/the_scribe.py
piwheels/protocols.py
tests/conftest.py
tests/master/test_cloud_gazer.py
tests/master/test_pypi.py
tests/master/test_the_scribe.py

 Store the latest package description and show it on the project page

---

piwheels/master/templates/faq.pt

- Re: #225 (@KTibow)
- Adds FAQ about sudo and pip3

Add sudo/pip3 FAQ

---

piwheels/importer/__init__.py
piwheels/slave/builder.py

Add option to piw-import to specify dependencies

---

piwheels/importer/__init__.py
piwheels/initdb/sql/create_piwheels.sql
piwheels/initdb/sql/update_piwheels_0.18_to_0.19.sql
piwheels/master/db.py
piwheels/master/mr_chase.py
piwheels/master/slave_driver.py
piwheels/master/templates/simple_package.pt
piwheels/master/the_scribe.py
piwheels/protocols.py
piwheels/slave/builder.py
piwheels/states.py
tests/conftest.py
tests/importer/test_importer.py
tests/master/test_db.py
tests/master/test_the_oracle.py
tests/master/test_the_scribe.py
tests/test_states.py

- Closes #208 
- Depends on #248 and #253 
TODO after deployment:
- Set Requires-Python field for all existing files

Implement Requires-Python

---

piwheels/format.py
piwheels/importer/__init__.py
piwheels/logger/__init__.py
piwheels/master/cloud_gazer.py
piwheels/master/pypi.py
piwheels/master/the_scribe.py
piwheels/slave/builder.py
tests/master/test_pypi.py
tests/slave/test_builder.py
tests/test_format.py
tests/test_info.py

Fix some failures in the Builder.metadata property and ldd dependency logic

Fix builder metadata

---

piwheels/master/pypi.py
tests/master/test_pypi.py

This is a hotfix now deployed on the master which fixes several timeout issues against the PyPI API which've interrupted the master in the past week.

Hotfix timeout

---

deploy_slave.sh

Revert "Replace cargo with rustup"

---

deploy_slave.sh

* Hopefully closes https://github.com/piwheels/packages/issues/197

Add golang to deploy_slave.sh

---

piwheels/importer/__init__.py

Fix dependences number on piw-import when no dependencies

---

piwheels/pypi.py

Handle TooManyRedirects in pypi_package_description

---

piwheels/master/static/sitemap.xsl

Update sitemap layout

---

deploy_slave.sh

Re: https://github.com/piwheels/packages/issues/319

Add fprint-dev

---

deploy_slave.sh

See https://github.com/piwheels/packages/issues/237#issuecomment-1221532850

Install Rust for piwheels user with rustup

---

deploy_slave.sh

Re: https://github.com/piwheels/packages/issues/336

Add libgirepository1.0-dev for PyGObject

---

.github/workflows/test.yml
Makefile
docs/master.rst
piwheels/platform.py
piwheels/slave/__init__.py
requirements_bookworm.txt
requirements_bullseye.txt
requirements_buster.txt
setup.cfg
tests/importer/test_importer.py
tox.ini

Drop Python 3.7, ensure we're testing 3.11 and switch to Ubuntu 22.04 on GitHub Actions

---

piwheels/initdb/__init__.py
piwheels/master/the_scribe.py
piwheels/master/vendor/_structures.py
piwheels/master/vendor/version.py
piwheels/master/version.py
tests/master/test_the_scribe.py
tests/master/test_version.py

Replace pkg_resources with importlib

---

piwheels/master/static/sitemap.xsl
piwheels/master/templates/faq.pt
piwheels/master/templates/index.pt
piwheels/master/templates/json.pt
piwheels/master/templates/layout.pt
piwheels/master/templates/packages.pt
piwheels/master/templates/project.pt

OpenGraph meta tags
